### ISSUE TITLE
Running new relay

### ISSUE THREAD

**Issue by BeastModeCicek** [ATOR-Development/ator-dashboard#128]
**Description**
Hi. I started running my ATOR relay today, but it still hasn't registered on the ATOR dashboard yet. My fingerprint is: 8F89DA37A9EAC81058C3DC0EE80AE0103D56E981. Thanks!

**Comment by jim-toth** [comment]
@BeastModeCicek hey!  thanks for posting :smile:

Since your relay is new to the network it's not being picked up by tor metrics just yet.  In order for a relay to be claimable in the registry (for you to see it on your dashboard) it has to be picked up by tor metrics and have a nonzero consensus weight.  Just a note: I searched for your relay fingerprint on tor metrics https://metrics.torproject.org/rs.html#details/8F89DA37A9EAC81058C3DC0EE80AE0103D56E981 and there was no result.

I'm going to close this for now, but if you notice at some point in the future that the above link is populated but your relay doesn't show up in the dashboard feel free to re-open and we'll investigate.
